config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :topics, except: :destroy

  delete '/topics/:name', to: 'topics#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing#index'

  get '/hashtags', to: 'hashtag#index'
  post '/hashtags/create', to: 'hashtag#batch_create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  # get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  resources :users, except: [:new]
  # post '/users' => 'users#create'

  get '/dashboard' => 'dashboard#index-2'
  get 'dashboard/settings' => 'dashboard#settings'
  get 'dashboard/hashtags' => 'dashboard#hashtags'

  get '/landing' => 'landing#index'

  get '/topic/hashtags' => 'topics#get_hashtags'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  belongs_to :topic

  def self.tweet_search(term)
    hashtag_collection = {}
    TwitterService.search(term).map do |tweets|
      tweets.hashtags.map do |hashtag|
        hashtag_name = hashtag.text.downcase
        if hashtag_collection.keys.include?(hashtag_name)
          hashtag_collection[hashtag_name] += 1;
        else
          hashtag_collection[hashtag_name] = 1;
        end
      end
    end
    hashtag_collection.sort_by{|key, value| value}.reverse
  end

  def self.batch_create(hashtags)
    hashtags[0..14].map do |hashtag|
      create(name: hashtag[:name], count: hashtag[:count])
    end
  end

end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :hashtags, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :topics
  has_many :hashtags, through: :topics
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :password, presence: true
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :login_required


  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @new_topic = Topic.new
    @topic = Topic.find_by(name: params[:topic_name]) || Topic.first
    #binding.pry
  end

  def settings
  end

  def hashtags
  end
end

app/controllers/hashtag_controller.rb
require 'twitter_search'

class HashtagController < ApplicationController

  def index
    if params[:hashtag_search]
      @results = Hashtag.tweet_search(params[:hashtag_search]).take(20)
    end
  end

  def batch_create
    topic_id = params[:topic].to_i
    params[:hashtag_values].each do |hashtag|
      Hashtag.create!(name: hashtag, count: params[hashtag].to_i, topic_id: topic_id)
    end
    redirect_to dashboard_path
  end

  private
  def hashtag_params
    params.require(:hashtags).permit(:hashtag_values, :name, :count)
  end

end

app/controllers/landing_controller.rb
require 'twitter_search'

class LandingController < ApplicationController
  def index
    if params[:q]
      @results = Hashtag.tweet_search(params[:q]).take(15)
    end
  end

  private
  def hashtag_params
    params.require(:hashtags).permit(:hashtag_values, :name, :count)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new
  end

  def create
  user = User.find_by_email(params[:email])
  # If the user exists AND the password entered is correct.
  if user && user.authenticate(params[:password])
    # Save the user id inside the browser cookie. This is how we keep the user
    # logged in when they navigate around our website.
    session[:user_id] = user.id
    redirect_to dashboard_path
  else
  # If user's login doesn't work, send them back to the login form.
    redirect_to login_path
  end
end

def destroy
  session[:user_id] = nil
  redirect_to '/'
end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authorize, only: [:new]

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    if @topic.save
      redirect_to dashboard_path
    else
      redirect_to new_topic_path
    end
  end

  def get_hashtags
    params[:topicName]
    redirect_to dashboard_path(topic_name: params[:topicName])
  end

  def destroy
    Topic.find_by(name: delete_topic_params).destroy
    respond_to do |format|
      format.html { redirect_to dashboard_path, notice: 'Topic was successfully deleted.' }
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:name)
  end

  def delete_topic_params
    params.require(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/', :notice => 'Signed Up!'
    else
      redirect_to '/signup'
    end
  end


  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/hashtag_helper.rb
module HashtagHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/_footer.html.erb
<!--Footer -->
<footer class='navbar-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-2'>
        <h4>TAGSNOOPER</h4>
        <ul class='list-unstyled'>
          <li><a href='/'>Home</a></li>
          <li><a href='#team'>About</a></li>
          <li><a href='#services'>Contact</a></li>
        </ul>
      </div>
      <div class='col-xs-2 col-xs-offset-1'>
        <h4>ACCOUNT</h4>
        <ul class='list-unstyled'>
          <li><a href='/login'>Log in</a></li>
          <li><a href='/signup'>Register</a></li>
        </ul>
      </div>
      <div class='col-md-2 col-md-offset-5 col-xs-3 col-xs-offset-4'>
        <h4>GET IN TOUCH</h4>
        <ul class='list-unstyled'>
          <li><a href='/'>info@tagsnooper.com</a></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="text-center">
        <ul class="icons">
          <li><a href="https://www.twitter.com" class="twitter ion-social-twitter"></a></li>
          <li><a href="https://www.facebook.com" class="facebook ion-social-facebook"></a></li>
          <li><a href="https://www.instagram.com" class="instagram ion-social-instagram"></a></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 col-md-offset-4 col-xs-4 col-xs-offset-4 text-center">
        <div class="copyright"><p>©2017 Tagsnooper. All Rights Reserved.<p></div>
      </div>
    </div>
  </div>
</footer>

app/views/dashboard/_navbar.html.erb
<!-- <div id="loading">
  <img id="loading-image" src="/assets/tagsnooper.gif" alt="Loading..." />
</div> -->
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand topnav" href="/"><img src="<%= asset_path 'tagsnooper-logo.png' %>" alt=""></a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="current-user">
                  <% if current_user %>
                    WELCOME, <%= current_user.name.upcase %>
                  <% end %>
                </li>
                <li>
                    <a href="/">Home</a>
                </li>
                <li>
                    <% if current_user %>
                    <%= link_to "Dashboard", '/dashboard' %>
                    <% else %>
                    <%= link_to "Dashboard", '/login' %>
                    <% end %>
                    <% yield %></a>
                </li>
                <li class="login-nav">
                  <% if current_user %>
                  <%= link_to "Log out", '/logout' %>
                  <% else %>
                  <%= link_to 'Log in', '/login' %>
                </li>
                <li class="signup-nav">
                  <%= link_to 'Sign up', '/signup' %>
                  <% end %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/dashboard/_newtopic.html.erb
<!-- Button trigger modal -->
<button type="button" class="new_topic_button btn btn-success" data-toggle="modal" data-target="#myModal">
  NEW TOPIC
</button>

<!-- Modal -->
<div class="container text-center">
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">CREATE</h4>
        </div>
        <div class="modal-body">
          <%= form_for @new_topic do |f| %>

            <div class="field">
              <%= f.label :name, remote: true %>
              <%= f.text_field :name, id: 'another_temp_id', remote: true %>
            </div>

        </div>
        <div class="modal-footer">
          <%= f.submit 'Create Topic', class: "submit_button btn btn-success", remote: true %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/hashtags.html.erb
<div class="stage">
  <div class="cell">


    <div class="searchbar">

      <input type="text" class="btn-extended" placeholder="search" />

      <div class="btn-search"></div>

    </div><!-- .searchbar -->



  </div><!-- .cell -->
</div><!-- .stage -->

app/views/dashboard/index-2.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-lg-2">
      <nav id="side-nav" class="navbar navbar-default navbar-fixed-side">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                  <a class="navbar-brand" href="/"><img src="<%= asset_path 'tagsnooper-logo.png' %>" alt=""></a>
                </li>
                <!-- <li>
                  <?%= form_tag("/hashtags", method: "get") do %>
                  <?%= text_field_tag (:hashtag_search), nil, placeholder: "Search", id: "hashtag_search", required: true, autofocus: true%>
                  <?% end %>
                </li> -->
                <li>
                    <a href="#">Create Topic</a>
                </li>
                <li>
                    <a href="#">Delete Topic</a>
                </li>
                <li>
                    <a href="#">Log out</a>
                </li>
            </ul>
      </nav>
    </div>
    <div class="col-sm-9 col-lg-10">
      <%= form_tag("/hashtags", method: "get") do %>
      <%# label_tag(:q, "Snoop for:") %>
      <%= text_field_tag (:hashtag_search), nil, placeholder: "Snoop for..", id: "hashtag_search", required: true, autofocus: true%>
      <%= button_tag ("SNOOP"), class: "btn-success", data: {disable_with: "<i class='fa fa-spinner fa-pulse fa-3x fa-fw'></i>"}%>
      <% end %>


      <% if defined?(@results) %>

      <%= form_tag hashtags_create_path, method: :post, class: "navbar-form navbar-left search-form" do %>
        <%= select_tag 'topic', options_from_collection_for_select(current_user.topics, 'id', 'name'), class: 'topic_search' %>
          <% @results.each do |user_hashtag, hashtag_count| %>
          <div class="hashtags col-lg-12">
            <div class="dropdownitem"><span style="color: #5899B9">#</span><%= user_hashtag.capitalize %>: <%= hashtag_count %>
              <input type="checkbox" value="<%= user_hashtag %>" name="hashtag_values[]">
            </div>
          </div>
          <% end %>
          <!-- <input class="btn btn-success submit_button" type="submit" value="SAVE SNOOPS"><a href="/dashboard"></a></input> -->
          <%= button_tag ("SAVE"), class: "btn-success" %>
        <% end %>

      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<%= render 'navbar' %>
<section id="dashintro">
   <div class="container">
     <div class="dashboard col-lg-12">
       <div class="dashboardnav">
         <h1 class="dashboardtitle"><a href="/dashboard"><img src="https://s14.postimg.org/dvkhc3u81/Tag_Snooper_Logo.png"></img></a>DASHBOARD</h1>
       </div>
         <div class="col-md-3">
           <ul>
             <li class="card card-block" style="width: 18rem; height:18rem">
               <h3 class="card-title">SEARCH HASHTAGS</h3>
               <p class="card-text">SEARCH SPECIFIC TOPICS FOR HASHTAGS</p>
               <a href="/hashtags"><button type="button" class="btn btn-primary">SEARCH</button></a>
             </li>

             <li class="card card-block" style="width: 18rem; height:18rem">
               <h3 class="card-title">NEW TOPIC</h3>
               <p class="card-text">CREATE A TOPIC FOR EACH SEARCH YOU WANT TO SAVE</p>
               <%= render 'newtopic' %>
             </li>

             <li class="card card-block" style="width: 18rem; height:16rem">
             <h3 class="card-title">Delete Topic</h3>
             <p class="card-text">Delete any topic you do not want anymore</p>
             <%= button_tag 'DELETE TOPIC', onclick: "deleteTopic()", class: "btn btn-danger" %>
             </li>
       </div>
       <div class="col-md-9">
         <ul>
           <li class="dropdown">
             <h3>MY TOPICS</h3>
               <% if @topic %>
               <div class="dropdown-content">
               <%= select_tag 'topic', options_from_collection_for_select(current_user.topics, 'id', 'name', @topic.id), id: "topic_search" %>
               <% end %>
             </div>
               <% if @topic %>
               <% @topic.hashtags.each do |ht| %>
               <div class="dropdownitem">
               <span style="color: #5899B9">#</span><%= ht.name.capitalize %>
               </div>
             <% end %>
           <% end %>
         </li>
       </ul>
     </div>
</section>


<%= render 'footer' %>

app/views/dashboard/settings.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Tagsnooper</title>

  </head>

  <body>

  </body>
</html>

app/views/hashtag/_footer.html.erb
<!--Footer -->
<footer class='navbar-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-2'>
        <h4>TAGSNOOPER</h4>
        <ul class='list-unstyled'>
          <li><a href='/'>Home</a></li>
          <li><a href='#team'>About</a></li>
          <li><a href='#services'>Contact</a></li>
        </ul>
      </div>
      <div class='col-xs-2 col-xs-offset-1'>
        <h4>ACCOUNT</h4>
        <ul class='list-unstyled'>
          <li><a href='/login'>Log in</a></li>
          <li><a href='/signup'>Register</a></li>
        </ul>
      </div>
      <div class='col-md-2 col-md-offset-5 col-xs-3 col-xs-offset-4'>
        <h4>GET IN TOUCH</h4>
        <ul class='list-unstyled'>
          <li><a href='/'>info@tagsnooper.com</a></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="text-center">
        <ul class="icons">
          <li><a href="https://www.twitter.com" class="twitter ion-social-twitter"></a></li>
          <li><a href="https://www.facebook.com" class="facebook ion-social-facebook"></a></li>
          <li><a href="https://www.instagram.com" class="instagram ion-social-instagram"></a></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 col-md-offset-4 col-xs-4 col-xs-offset-4 text-center">
        <div class="copyright"><p>©2017 Tagsnooper. All Rights Reserved.<p></div>
      </div>
    </div>
  </div>
</footer>

app/views/hashtag/_navbar.html.erb
<!-- <div id="loading">
  <img id="loading-image" src="/assets/tagsnooper.gif" alt="Loading..." />
</div> -->
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand topnav" href="/"><img src="<%= asset_path 'tagsnooper-logo.png' %>" alt=""></a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="current-user">
                  <% if current_user %>
                    WELCOME, <%= current_user.name.upcase %>
                  <% end %>
                </li>
                <li>
                    <a href="/">Home</a>
                </li>
                <li>
                    <% if current_user %>
                    <%= link_to "Dashboard", '/dashboard' %>
                    <% else %>
                    <%= link_to "Dashboard", '/login' %>
                    <% end %>
                    <% yield %></a>
                </li>
                <li class="login-nav">
                  <% if current_user %>
                  <%= link_to "Log out", '/logout' %>
                  <% else %>
                  <%= link_to 'Log in', '/login' %>
                </li>
                <li class="signup-nav">
                  <%= link_to 'Sign up', '/signup' %>
                  <% end %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/hashtag/index.html.erb
<%= render 'navbar' %>
<section id="hashintro">
  <div class="container">
    <div class="dashboard col-lg-12">
      <div class="dashboardnav">
        <h1 class="dashboardtitle"><a href="/dashboard"><img src="https://s14.postimg.org/dvkhc3u81/Tag_Snooper_Logo.png"></img></a>SEARCH</h1>
      </div>
      <div class="col-md-12">

        <%= form_tag("/hashtags", method: "get") do %>
        <%# label_tag(:q, "Snoop for:") %>
        <%= text_field_tag (:hashtag_search), nil, placeholder: "Snoop for..", id: "hashtag_search", required: true, autofocus: true%>
        <%= button_tag ("SNOOP"), class: "btn-success", data: {disable_with: "<i class='fa fa-spinner fa-pulse fa-3x fa-fw'></i>"}%>
        <% end %>


        <% if defined?(@results) %>

        <%= form_tag hashtags_create_path, method: :post, class: "navbar-form navbar-left search-form" do %>
          <%= select_tag 'topic', options_from_collection_for_select(current_user.topics, 'id', 'name'), class: 'topic_search' %>
            <% @results.each do |user_hashtag, hashtag_count| %>
            <div class="hashtags col-lg-12">
              <div class="dropdownitem"><span style="color: #5899B9">#</span><%= user_hashtag.capitalize %>: <%= hashtag_count %>
                <input type="checkbox" value="<%= user_hashtag %>" name="hashtag_values[]">
              </div>
            </div>
            <% end %>
            <!-- <input class="btn btn-success submit_button" type="submit" value="SAVE SNOOPS"><a href="/dashboard"></a></input> -->
            <%= button_tag ("SAVE"), class: "btn-success" %>
          <% end %>

        <% end %>
    </div>
  </div>
</section>
<%= render 'footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tagsnoop</title>
    <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Muli Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli:300" rel="stylesheet">

    <!-- Ion Icons -->
    <link href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>
  <body>
    <%= yield %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->

  </body>
</html>

app/views/topics/new.html.erb
<%= form_for @topic do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_navbar.html.erb
<!-- <div id="loading">
  <img id="loading-image" src="/assets/tagsnooper.gif" alt="Loading..." />
</div> -->
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand topnav" href="/"><img src="<%= asset_path 'tagsnooper-logo.png' %>" alt=""></a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="/">Home</a>
                </li>
                <li>
                    <% if current_user %>
                    <%= link_to "Dashboard", '/dashboard' %>
                    <% else %>
                    <%= link_to "Dashboard", '/login' %>
                    <% end %>
                    <% yield %></a>
                </li>
                <li class="login-nav">
                  <% if current_user %>
                  <%= link_to "Log out", '/logout' %>
                  <% else %>
                  <%= link_to 'Log in', '/login' %>
                </li>
                <li class="signup-nav">
                  <%= link_to 'Sign up', '/signup' %>
                  <% end %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'navbar' %>
<section id="login">
  <div class="container">
    <div class="row">
      <div class="login col-md-7 col-xs-7">
        <div class="login-text">
        	<h2>SIGN UP</h2>
          <p>Please fill out the required fields below.</p>
            <%= form_for :user, url: '/users' do |f| %>
            	<%= f.text_field :name, placeholder: "Name", :autofocus=>true %>
              <%= f.text_field :email, placeholder: "Email"%>
        			<%= f.password_field :password, placeholder: "Password" %>
        			<%= f.password_field :password_confirmation, placeholder: "Password Confirmation" %>
              <%= f.submit "SUBMIT", class: "submit btn btn-primary btn-block btn-large" %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>